"""new fields in user model

Revision ID: 949d7f4bdfe8
Revises: f5d6cd72bece
Create Date: 2023-06-27 02:08:54.800736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '949d7f4bdfe8'
down_revision = 'f5d6cd72bece'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
